# Generated by Django 4.1 on 2022-11-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('codigoConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=35)),
                ('consulta', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('codigoRespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTecnico', models.CharField(max_length=35)),
                ('respuesta', models.CharField(max_length=500)),
            ],
        ),
    ]
