# Generated by Django 4.1 on 2022-11-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultas',
            old_name='codigoConsulta',
            new_name='codigoConsultaClien',
        ),
        migrations.RenameField(
            model_name='respuesta',
            old_name='codigoRespuesta',
            new_name='CodigoRespuestaTec',
        ),
        migrations.AddField(
            model_name='consultas',
            name='codigoRespuestaClien',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='codigoConsultaTec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online.consultas', verbose_name='Codigo Consulta'),
            preserve_default=False,
        ),
    ]
